CREATE TABLE IF NOT EXISTS Films (
                       film_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar NOT NULL,
                       description varchar,
                       releaseDate date,
                       duration int,
                       rating_id int
);

CREATE TABLE IF NOT EXISTS Users (
                       user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       login varchar NOT NULL,
                       name varchar,
                       email varchar,
                       birthday date
);

CREATE TABLE IF NOT EXISTS Likes (
                       user_id int,
                       film_id int,
                       PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS Friendship (
                            user_id int,
                            friend_id int,
                            confirmed boolean,
                            PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS Genre (
                       genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS FilmGenre (
                           film_id int,
                           genre_id int,
                           PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS Rating (
                        rating_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar UNIQUE NOT NULL
);

COMMENT ON COLUMN Friendship.confirmed IS 'Friendship status';

ALTER TABLE Films ADD FOREIGN KEY (rating_id) REFERENCES Rating (rating_id);

ALTER TABLE Friendship ADD FOREIGN KEY (user_id) REFERENCES Users (user_id);

ALTER TABLE Friendship ADD FOREIGN KEY (friend_id) REFERENCES Users (user_id);

ALTER TABLE FilmGenre ADD FOREIGN KEY (genre_id) REFERENCES Genre (genre_id);

ALTER TABLE FilmGenre ADD FOREIGN KEY (film_id) REFERENCES Films (film_id);

ALTER TABLE Likes ADD FOREIGN KEY (film_id) REFERENCES Films (film_id);

ALTER TABLE Likes ADD FOREIGN KEY (user_id) REFERENCES Users (user_id);
